spring:
  data:
    mongodb:
      uri: mongodb + srv ://<username>:<pwd>@<cluster>.mongodb.net/<dbname>

resilience4j.retry:
  configs:
    default:
      maxAttempts: 10
      waitDuration: 1000ms
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
      ignoreExceptions: []
    exampleClient:
      maxAttempts: 10
      waitDuration: 1000ms
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
      ignoreExceptions: [ ]

example:
  url: "some/url"
  read-timeout: 1000ms
  connect-timeout: 1000ms
