name: Kotlin CI

on:
  pull_request:
    branches:
      - "main"

jobs:
  ktlintCheck:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Run ktlintCheck
      run: ./gradlew ktlintCheck

  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run tests
        run: ./gradlew test
  ticketValidation:
    uses: Group-Expense-Manager/common-ci-cd/.github/workflows/jira.yml@main