name: Build and Push Docker Image

on:
  push:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        env:
          USERNAME: ${{ github.ref_name }}
          TOKEN: ${{ secrets.LIB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        env:
          USERNAME: ${{ github.ref_name }}
          TOKEN: ${{ secrets.LIB_TOKEN }}
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest
